apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: oauth-demo3
spec:
  dnsExternalAlias:
    - alias: one.example.com
      environment: dev
      component: web
    - alias: two.example.com
      environment: dev
      component: web
  environments:
    - name: dev
      build:
        from: main
  components:
    - name: web
      variables:
        ASPNETCORE_URLS: http://*:5005
      ports:
        - name: http
          port: 5005
      publicPort: http
