# yaml-language-server: $schema=file:///home/nst/go/src/github.com/equinor/radix-operator/json-schema/radixapplication.json
apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: oauth-demo2
spec:
  environments: []
  components:
    - name: web
      image: nginxinc/nginx-unprivileged:1.31.3-alpine3.24
      ports:
        - name: http
          port: 8080
      publicPort: http

