--- 
# Anchor definitions

x-default-resources: &default-resources
  resources:
    requests:
      memory: "150M"
      cpu: "100m"
    limits:
      memory: "500M"
      cpu: "100m"

x-prod-resources: &prod-resources
  resources:
    requests:
      memory: "150M"
      cpu: "100m"
    limits:
      memory: "500M"
      cpu: "100m"

x-horizontal-scaling: &horizontal-scaling
  horizontalScaling:
    minReplicas: 1
    maxReplicas: 3


x-azure-blob1: &azure-blob1
  type: azure-blob
  name: volume-name1
  storage: container-name1
  path: /path/in/container/to/mount/to1

x-azure-blob2: &azure-blob2
  type: azure-blob
  name: volume-name2
  storage: container-name2
  path: /path/in/container/to/mount/to2

x-keyvault1: &keyvault1
  name: radix-app-secrets
  path: /mnt/key-vault
  items:
    - name: connection-string-dev
      type: secret
      envVar: CONNECTION_STRING

x-keyvault2: &keyvault2
  name: radix-app-secrets2
  path: /mnt/key-vault2
  items:
    - name: key1
      type: key
      envVar: KEY1
    - name: cert1
      type: cert
      envVar: CERT1

x-secret-refs: &secret-refs
  azureKeyVaults: [*keyvault1, *keyvault2]

x-common-vars: &common-vars
  VAR1: foo
  VAR2: bar

x-aspnet-vars: &web-vars
  web1: foo-web
  web2: bar-web

x-prod: &prod prod
x-dev: &dev dev

# radixconfig
apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: oauth-demo2
spec:
  environments:
    - name: *prod
      build:
        from: release
    - name: *dev
      build:
        from: main
  components:
    - name: web
      <<: *default-resources
      variables:
        <<: [*common-vars, *web-vars]
        ASPNETCORE_URLS: http://*:5005
      ports:
        - name: http
          port: 5005
      publicPort: http
      secretRefs: *secret-refs
      environmentConfig:
        - environment: *prod
          <<: [*prod-resources, *horizontal-scaling]
          volumeMounts: [*azure-blob1, *azure-blob2]
    - name: web2
      <<: *default-resources
      variables:
        <<: *common-vars
        ASPNETCORE_URLS: http://*:5006
      ports:
        - name: http
          port: 5006
      publicPort: http
      secretRefs: *secret-refs
      environmentConfig:
        - environment: *prod
          <<: [*prod-resources, *horizontal-scaling]
          volumeMounts: [*azure-blob1]
