apiVersion: tekton.dev/v1beta1 # or tekton.dev/v1beta1
kind: PipelineRun
metadata:
  namespace: oauth-demo-app
  generateName: pipeline-
spec:
  pipelineRef:
    name: pipeline
  params:
    - name: radix
      value:
        git-ssh-url: aspnetsshurl
        git-commit: "oxfffffaaaaa"
  # params:
  #   - name: sshurl
  #     value: mysshurl
  #   - name: commit
  #     value: mycommit
