apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline
  namespace: oauth-demo-app
spec:
  params:
    - name: VAR_A
      default: vara
    - name: VAR_B
      default: varb
    - name: VAR_C
      default: varc
    - name: ALPINE_IMAGE
      default: alpine:latest
    - name: UNDEFINED
      default: dflt
  tasks:
    - name: some-build-task
      taskRef:
        name: chat
      params:
        - name: VAR_A
          value: $(params.VAR_A)
        - name: VAR_B
          value: $(params.VAR_B)
        - name: VAR_C
          value: $(params.VAR_C)
        - name: ALPINE_IMAGE
          value: $(params.ALPINE_IMAGE)
    - name: test-github
      taskRef:
        name: test-github
