apiVersion: tekton.dev/v1beta1 # or tekton.dev/v1beta1
kind: TaskRun
metadata:
  namespace: oauth-demo-app
  generateName: chat-
spec:
  params:
  - name: radix
    value:
      git-ssh-url: xyz.com
      git-commit: sha123
  - name: not-defined
    value: "undefined value"
  taskRef:
    name: chat