apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: chat
  namespace: oauth-demo-app
  labels:
    azure.workload.identity/use: "true"
spec:
  # volumes:
  #   - name: host-fs
  #     hostPath:
  #       path: /
  # params:
  #   - name: radix
  #     type: object
  #     properties:
  #       git-ssh-url:
  #         type: string
  #       git-commit:
  #         type: string
  params:
    - name: VAR_A
      default: vara_task
    - name: VAR_B
      default: varb_task
    - name: VAR_C
      default: varc_task
    - name: VAR_D
      default: vard_task
  steps:
  - image: alpine
    name: sayhello
    securityContext:
      privileged: false
      allowPrivilegeEscalation: false
      runAsUser: 1000
    # env:
    #   - name: GIT_SSH_URL
    #     value: $(params.radix.git-ssh-url)
    #   - name: GIT_COMMIT
    #     value: $(params.radix.git-commit)
    volumeMounts:
      - name: $(radix.git-deploy-key) # <-- This volume is created by Radix and available where you mount it.
        mountPath: /.ssh
    # volumeMounts:
    # - name: host-fs
    #   mountPath: /host
    script: |
      #!/usr/bin/env sh
      echo hello 63 $(hostname)
      echo ""
      printenv
      echo ""
      echo "VAR_A: $(paras.VAR_A)"
      echo "VAR_B: $(paras.VAR_B)"
      echo "VAR_C: $(paras.VAR_C)"
      echo "VAR_D: $(paras.VAR_D)"
      echo ""
      id
      echo ""
      ls -Ahl
      # ls /host -l
      # cat <<EOF > /host/tmp/pod.yaml
      # apiVersion: v1
      # kind: Pod
      # metadata:
      #   name: alpine
      #   namespace: default
      # spec:
      #   containers:
      #   - name: alpine
      #     image: alpine
      #     command: ["/bin/sh"]
      #     args: ["-c", "sleep 30"]
      # EOF
      # chroot /host kubectl apply -f /tmp/pod.yaml --kubeconfig=/var/lib/kubelet/kubeconfig
      :
  - image: alpine
    name: saygoodbye
    securityContext:
      privileged: false
      allowPrivilegeEscalation: false
      runAsUser: 1000
    script: |
      #!/usr/bin/env sh
      echo goodbye $(hostname)
      :

