apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: chat
  namespace: oauth-demo-app
  labels:
    azure.workload.identity/use: "true"
spec:
  # volumes:
  #   - name: host-fs
  #     hostPath:
  #       path: /
  # params:
  #   - name: radix
  #     type: object
  #     properties:
  #       gitSSHUrl:
  #         type: string
  #       gitCommit:
  #         type: string

  steps:
  - image: alpine
    name: sayhello
    securityContext:
      privileged: false
      allowPrivilegeEscalation: false
      runAsUser: 1000
    # env:
    #   - name: GIT_SSH_URL
    #     value: $(params.radix.gitSSHUrl)
    #   - name: GIT_COMMIT
    #     value: $(params.radix.gitCommit)
    volumeMounts:
      - name: $(radix.git-deploy-key) # <-- This volume is created by Radix and available where you mount it.
        mountPath: /.ssh
    # volumeMounts:
    # - name: host-fs
    #   mountPath: /host
    script: |
      #!/usr/bin/env sh
      echo hello 63 $(hostname)
      printenv
      id
      ls -Ahl
      # ls /host -l
      # cat <<EOF > /host/tmp/pod.yaml
      # apiVersion: v1
      # kind: Pod
      # metadata:
      #   name: alpine
      #   namespace: default
      # spec:
      #   containers:
      #   - name: alpine
      #     image: alpine
      #     command: ["/bin/sh"]
      #     args: ["-c", "sleep 30"]
      # EOF
      # chroot /host kubectl apply -f /tmp/pod.yaml --kubeconfig=/var/lib/kubelet/kubeconfig
      :
  - image: alpine
    name: saygoodbye
    securityContext:
      privileged: false
      allowPrivilegeEscalation: false
      runAsUser: 1000
    script: |
      #!/usr/bin/env sh
      echo goodbye $(hostname)
      :

