apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: test-github
spec:
  stepTemplate:
    securityContext:
      runAsUser: 65534 # nobody

  steps:
    - name: print-context
      image: alpine
      script: |
        #!/usr/bin/env sh
        echo "Pipeline type: $(params.radix.pipeline-type)"
        echo "Environment: $(params.radix.environment)"
        echo "Git ref: $(params.radix.git-ref)"
        echo "Git commit: $(params.radix.git-commit)"

    - name: git-clone
      image: alpine/git
      volumeMounts:
        - name: $(radix.git-deploy-key) # <-- This volume is created by Radix and available where you mount it.
          mountPath: /.ssh
        - name: source-volume
          mountPath: /var/source
      script: |
        #!/usr/bin/env sh
        git clone "$(params.radix.git-ssh-url)" /var/source/app
        cd /var/source/app
        git checkout "$(params.radix.git-commit)"

    - name: list-contents
      image: alpine
      volumeMounts:
        - name: source-volume
          mountPath: /var/source
      script: |
        #!/usr/bin/env sh
        ls -lah /var/source/app

  volumes:
    - name: source-volume
      emptyDir: { }
