server {
    listen 8080;

    root /usr/share/nginx/html;
    index index.html;

    # # set_real_ip_from 192.168.65.1; # IP address of your trusted proxy/load balancer
    # set_real_ip_from 10.0.0.0/8; # IP address of your trusted proxy/load balancer. CIDR range for pod subnet. Only Istio and Prometheus can do cross-namespace requests. NB: This will still allow pods in same namespace to act as proxies
    # real_ip_header X-Forwarded-For; # The header where the real IP is stored
    
    # # If there are multiple intermediate proxies, use:
    # real_ip_recursive off;

    location / {
        # allow 143.97.110.1;           # Specific IP address allowed
        # allow 143.97.110.1/24;       # IP address range allowed (CIDR notation)
        # deny all; 
        try_files $uri $uri/ =404;
        # proxy_pass http://web:5005/;
    }
}
