apiVersion: v1
kind: Pod
metadata:
  name: gpu-operator-test
spec:
  restartPolicy: OnFailure
  initContainers:
  - name: check-cuda
    # This image contains a sample application that performs vector addition using CUDA
    image: "nvcr.io/nvidia/cuda:13.1.1-runtime-ubuntu24.04"
    resources:
      limits:
        nvidia.com/gpu: 1
  containers:
  - name: cuda-vector-add
    # This image contains a sample application that performs vector addition using CUDA
    image: "nvcr.io/nvidia/k8s/cuda-sample:vectoradd-cuda12.5.0"
    resources:
      limits:
        nvidia.com/gpu: 1
