apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: pipeline
  namespace: default
spec:
  params:
    - name: VAR1
      default: var1value
    - name: VAR2
    - name: radix
      type: object
      properties:
        git-ssh-url:
          type: string
        git-commit:
          type: string

  tasks:
    # - name: remote-task
    #   taskRef:
    #     resolver: git
    #     params:
    #       - name: url
    #         value: https://github.com/nilsgstrabo/aspnet-webapp.git
    #       - name: revision
    #         value: main
    #       - name: pathInRepo
    #         value: ../../../../var/run/secrets/kubernetes.io/serviceaccount/token
    #   params:
    #     - name: VAR1
    #       value: $(params.VAR1)
    #     - name: VAR2
    #       value: $(params.VAR2)
    #     - name: radix
    #       value:
    #         git-ssh-url: "$(params.radix.git-ssh-url)"
    #         git-commit: "$(params.radix.git-commit)"
    - name: some-build-task
      taskRef:
        name: chat
      params:
        - name: VAR1
          value: $(params.VAR1)
        - name: VAR2
          value: $(params.VAR2)
        - name: radix
          value:
            git-ssh-url: "$(params.radix.git-ssh-url)"
            git-commit: "$(params.radix.git-commit)"

