name: Docker Image CI

on:
  push:
    branches: [ main ]


jobs:

  deploy-db:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - registry: radixdev
            client-id: CLIENT_ID_DEV
          - registry: radixprod
            client-id: CLIENT_ID_PROD
          - registry: radixc2prod
            client-id: CLIENT_ID_PROD

    steps:
      - name: echo
        run: echo $CLIENT_ID
        env:
          CLIENT_ID: ${{ matrix.client-id }}
    # - uses: actions/checkout@v3
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
