name: Docker Image CI

on:
  push:
    branches: [ main ]


jobs:

  deploy-db:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - registry: radixdev
            client-id-secret: CLIENT_ID_DEV
          - registry: radixprod
            client-id-secret: CLIENT_ID_PROD
          - registry: radixc2prod
            client-id-secret: CLIENT_ID_PROD

    steps:
      - name: echo
        run: |
          echo start
          echo ${{ matrix.client-id-secret }}
          echo ${{ secrets[matrix.client-id-secret] }}
          echo end
    # - uses: actions/checkout@v3
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
