name: deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment name'
        required: true
        default: 'dev'

permissions:
  id-token: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      myenv: abcd
    steps:
      - name: 'is go installed'
        run: |
          go version
      - name: 'env test'
        run: 'echo ${{ env.myenv }}'
      - name: 'Az CLI login'
        uses: azure/login@v2
        with:
          client-id: 5e48ca1f-a2bf-4dec-b96d-bbf8ce69f9f6 #b96d264b-7053-4465-a4a7-32be5b0fec49 #app registration appid or managed identity clientid
          tenant-id: 3aa4a235-b6e2-48d5-9195-7fcf05b459b0
          allow-no-subscriptions: true
      - name: 'Get Azure principal token for Radix'
        run: |
          token=$(az account get-access-token --resource 6dae42f8-4368-4678-94ff-3960e28e3630 --query=accessToken -otsv)
          echo "::add-mask::$token"
          echo "APP_SERVICE_ACCOUNT_TOKEN=$token" >> $GITHUB_ENV
      - name: List apps1
        uses: equinor/radix-github-actions@v1
        with:
          args: >
            get
            application
            --context development
      - name: Get oauth-demo
        uses: equinor/radix-github-actions@v1
        with:
          args: >
            get
            application
            --application oauth-demo
            --context development            
      - name: Run deploy
        uses: equinor/radix-github-actions@v1
        with:
          args: >
            create
            job
            deploy
            --application oauth-demo
            --environment $ENVIRONMENT
            --follow
            --context development
        env:
          ENVIRONMENT: ${{ inputs.environment }}