name: Prepare release pull requests
on:
  push: 
    tags:
      - '**'
    branches: 
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}

jobs:
  prepare-release-pr:
    name: Generate release PR
    permissions:
      contents: write
      pull-requests: write
      issues: write
    uses: equinor/radix-reusable-workflows/.github/workflows/template-prepare-release-pr.yml@v1.1.0
    with:
      branch: main
      generate-pre-release-pr: true
      extra-files:
        web/run.sh
      # changelog-path: CHANGELOG.md
      # cliff-config-path: cliff.toml


    
