name: Test
on:
    push: 
        tags:
            - '**'
        branches: 
            - main
    workflow_dispatch:


jobs:
  pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
        - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
          with:
            fetch-depth: 0
            ref: main
            # persist-credentials: false
        - name: set version
          run: |
            echo date > version.txt
        - name: create pr
          uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
          with:
            base: main
            delete-branch: true
            title: "chore: test pr"
            # branch: release/stable-release
            labels: "test"
            body: Hello there
            commit-message: "chore: test pr"
            sign-commits: true
            add-paths: |
              version.txt



    
